// Generated by Quality Playbook v1.5.6 — https://github.com/andrewstellman/quality-playbook
// Author: Andrew Stellman · Date: 2026-07-24 · Project: nexus-nexkit-vscode

import * as assert from "assert";
import * as fs from "fs";
import * as path from "path";

describe("Quality Playbook Functional Requirements", () => {
  const root = path.resolve(__dirname, "..");
  const packageJsonPath = path.join(root, "package.json");
  const extensionTsPath = path.join(root, "src", "extension.ts");
  const mcpServicePath = path.join(root, "src", "features", "mcp-management", "mcpConfigService.ts");
  const watcherPath = path.join(root, "src", "features", "nexkit-file-watcher", "nexkitFileWatcherService.ts");
  const workflowRunnerPath = path.join(root, "src", "features", "github-workflow-runner", "githubWorkflowRunnerService.ts");
  const extensionTestPath = path.join(root, "test", "suite", "extension.test.ts");

  const read = (p: string): string => fs.readFileSync(p, "utf8");

  it("REQ-001: contributed commands include core Nexkit actions", () => {
    const pkg = JSON.parse(read(packageJsonPath));
    const commandIds = new Set((pkg.contributes?.commands ?? []).map((c: { command: string }) => c.command));
    [
      "nexus-nexkit-vscode.initWorkspace",
      "nexus-nexkit-vscode.updateInstalledTemplates",
      "nexus-nexkit-vscode.addDevOpsConnection",
      "nexus-nexkit-vscode.openConvertToMarkdown",
    ].forEach((id) => assert.ok(commandIds.has(id), `Missing command contribution: ${id}`));
  });

  it("REQ-002: extension wires global error handlers", () => {
    const text = read(extensionTsPath);
    assert.ok(text.includes('process.on("unhandledRejection"'), "Expected unhandledRejection handler");
    assert.ok(text.includes('process.on("uncaughtException"'), "Expected uncaughtException handler");
    assert.ok(text.includes("isNexkitOwnedException"), "Expected ownership filter in global error path");
  });

  it("REQ-003: startup verification currently invokes auth check", () => {
    const text = read(extensionTsPath);
    assert.ok(text.includes("startupVerification.verifyOnStartup()"), "Expected startup verification invocation");
  });

  it("REQ-004: watcher change/delete handlers perform restore writes", () => {
    const text = read(watcherPath);
    assert.ok(text.includes("await fs.promises.writeFile(filePath, originalContent"), "Expected original-content restore write");
    assert.ok(text.includes("await fs.promises.unlink(filePath)"), "Expected delete path for keep/delete decision");
  });

  it("REQ-005: watcher startup defines event subscriptions", () => {
    const text = read(watcherPath);
    assert.ok(text.includes("createFileSystemWatcher"), "Expected file system watcher creation");
    assert.ok(text.includes("onDidChange"), "Expected change subscription");
    assert.ok(text.includes("onDidCreate"), "Expected create subscription");
    assert.ok(text.includes("onDidDelete"), "Expected delete subscription");
  });

  it("REQ-006/007: MCP update path contains parse fallback and write path", () => {
    const text = read(mcpServicePath);
    assert.ok(text.includes("config = JSON.parse(content)"), "Expected JSON parse of existing MCP config");
    assert.ok(text.includes("config = { servers: {} }"), "Expected fallback initializer");
    assert.ok(text.includes("await fs.promises.writeFile(configPath"), "Expected persisted config write");
  });

  it("REQ-008: workflow runner has OS-specific command builders", () => {
    const text = read(workflowRunnerPath);
    assert.ok(text.includes("buildPowerShellScriptArgs"), "Expected PowerShell command builder");
    assert.ok(text.includes("buildShellScriptArgs"), "Expected POSIX shell command builder");
    assert.ok(text.includes("terminal.sendText(command)"), "Expected terminal command dispatch");
  });

  it("REQ-009: convert workflow is exposed to users", () => {
    const pkg = JSON.parse(read(packageJsonPath));
    const commandIds = new Set((pkg.contributes?.commands ?? []).map((c: { command: string }) => c.command));
    assert.ok(commandIds.has("nexus-nexkit-vscode.openConvertToMarkdown"), "Expected convert command contribution");
  });

  it("REQ-010: extension command contract tests contain skipped coverage that must be remediated", () => {
    const text = read(extensionTestPath);
    assert.ok(text.includes("test.skip"), "Expected evidence of skipped activation contract tests");
  });

  it("REQ-011: auth helper defaults include repo scope", () => {
    const helperPath = path.join(root, "src", "shared", "utils", "githubAuthHelper.ts");
    const text = read(helperPath);
    assert.ok(text.includes('scopes: string[] = ["repo"]') || text.includes('scopes: string[] = ["repo"]'.replace(/ /g, "")) || text.includes('scopes: string[] = ["repo"]'), "Expected default repo scope");
  });

  it("REQ-012: startup verification invokes workspace config deploy flow", () => {
    const startupPath = path.join(root, "src", "features", "initialization", "startupVerificationService.ts");
    const text = read(startupPath);
    assert.ok(text.includes("verifyWorkspaceConfiguration"), "Expected workspace verification flow");
    assert.ok(text.includes("deployGitExclude"), "Expected git exclude deploy step");
  });
});
